name: masaj
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.6+9

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_animarker: ^3.2.0
  flutter_slidable: ^3.0.1
  uuid:
  cached_network_image: ^3.2.1
  cached_network_svg_image: ^1.1.0
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  flutter_typeahead: ^5.0.1
  restart_app: ^1.2.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  geocoding: ^3.0.0
  dartz: ^0.10.1
  get_it: ^8.0.0
  dio: ^5.3.3
  dotted_border: ^2.0.0+3
  easy_localization: ^3.0.7
  firebase_analytics: ^11.3.4
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.4
  firebase_messaging: ^15.1.4
  firebase_dynamic_links: ^6.0.9
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.3.7
  flutter_svg: ^2.0.9
  flutter_wallet:
    git:
      url: "https://github.com/benunes01/flutter_wallet_pkpass"
  font_awesome_flutter: ^10.4.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.2.3
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image_picker: ^1.0.4
  lazy_load_scrollview: ^1.3.0
  package_info_plus: ^8.0.0
  path_provider: ^2.0.11
  permission_handler: ^11.0.1
  requests_inspector: ^4.0.4
  rxdart: ^0.28.0
  root_check: ^0.0.2+1
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.3
  size_helper: ^2.0.0
  url_launcher: ^6.1.5
  video_player: ^2.5.1
  youtube_player_flutter: ^9.1.1
  flutter_screenutil: ^5.9.0
  gradient_borders: ^1.0.0
  map_location_picker: ^1.2.8+3
  intl_phone_field:
    git:
      url: https://github.com/muhammad369/intl_phone_field.git
      ref: master
  flutter_svg_provider: ^1.0.7
  outline_gradient_button: ^2.0.1+1
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.3.2
  gradient_icon: ^2.0.8
  country_flags: ^3.0.0
  dotted_line: ^3.2.2
  flutter_datetime_picker_plus: ^2.1.0
  bottom_picker: ^2.4.0
  pay: ^2.0.0
  loader_overlay: ^4.0.0
  upgrader: ^11.3.0
#  adjust_sdk: ^5.0.2
  flutter_widget_from_html: ^0.15.2


  # flutter_datetime_picker: ^1.5.1
  # fluttertoast: ^8.2.4

dependency_overrides:
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_gen_runner:
  change_app_package_name: ^1.1.0
  mocktail: ^1.0.4


flutter:
  # The following line ensures that the Material Icons font is included
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Almarai
      fonts:
        - asset: assets/fonts/AlmaraiRegular.ttf
          weight: 400
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/SofiaProBold.ttf
          weight: 700
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScriptMedium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400

flutter_native_splash:
  color: "#000000"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  image: assets/images/Bg.png
  background_image: assets/images/Bg.png
