// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCeTF6WO3zmE5PqhIyWSy0ZosC14fqKU',
    appId: '1:63212711751:android:49939e89b12b215d116662',
    messagingSenderId: '63212711751',
    projectId: 'padel-rush',
    storageBucket: 'padel-rush.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK1_IhoVSX4-bAza8wyve3NpcNcjRNYD8',
    appId: '1:63212711751:ios:46f8037339223a61116662',
    messagingSenderId: '63212711751',
    projectId: 'padel-rush',
    storageBucket: 'padel-rush.appspot.com',
    androidClientId:
        '63212711751-d0bgdv9keueon76o8jjp2l24u9ig5h84.apps.googleusercontent.com',
    iosClientId:
        '63212711751-d9muvvreerkqvgmjrb2fa5mghfbthvlt.apps.googleusercontent.com',
    iosBundleId: 'sa.sela.padel',
  );
}
