// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk41f1NXpIksRFniV8ihz-xywh9dtGGp8',
    appId: '1:115887106741:android:49ab71222ac64f25dc2cfc',
    messagingSenderId: '115887106741',
    projectId: 'masaj-23e10',
    storageBucket: 'masaj-23e10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoPd7fzdpXYkJoW2J6lEzXKWaElmQH1w',
    appId: '1:115887106741:ios:9531d4884d9c814edc2cfc',
    messagingSenderId: '115887106741',
    projectId: 'masaj-23e10',
    storageBucket: 'masaj-23e10.appspot.com',
    androidClientId: '115887106741-2dsr7fp1d5j03kfoouf5rjn7m7epb792.apps.googleusercontent.com',
    iosClientId: '115887106741-3mrp1nltv1b8r39t2gr1umrfqt2260gi.apps.googleusercontent.com',
    iosBundleId: 'com.masajapp',
  );
}
